version: '3.8'

services:
  backend:
    build: ./back
    command: python manage.py collectstatic --no-input
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/:/usr/src/back/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  frontend:
    build: front
    command: npm start
    volumes:
      - ./front/:/usr/src/front/
    ports:
      - "3000:3000"
volumes:
  static_volume:
